# Generated by Django 3.2.4 on 2021-07-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210630_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='body',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='question',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='title',
            new_name='topic',
        ),
    ]
